PAS-162 show reader fullname on navbar
team-four-cdc/team-four-cdc-FE pull request #68
Opened 2023-06-27 13:31 UTC by sluxzer

2023-07-03 15:19 UTC, chadwithz requested changes

2023-07-03 15:19 UTC, chadwithz commented on src/pages/api/login.ts
> +    req.session.auth = { ...auth, fullName, token, isLogin: true } as IUser
remove this fullName

2023-07-04 02:41 UTC, sluxzer commented on src/pages/api/login.ts
> +    req.session.auth = { ...auth, fullName, token, isLogin: true } as IUser
@chadwithz done mas, monggo di cek lagi

2023-07-04 03:01 UTC, chadwithz approved these changes

2023-07-04 03:01 UTC, merged